### ISSUE TITLE
Checkout COGDumper

### ISSUE THREAD

**Issue by vincentsarago** [geospatial-jeff/async-cog-reader#1]
👋 @geospatial-jeff 
The subject looks interesting 😄 

Not sure what's your idea but if we want to go full async maybe we can use some of the code from https://github.com/mapbox/COGDumper to go GDAL Free ...

COGDumper is not smart and doesn't do any spatial stuff but if we add pyproj we might be able to do; 
- get geospatial info from the COG
- fetch only the internal tile (and overview tiles) for a specific `.read` request.

**Comment by geospatial-jeff** [comment]
> GDAL Free ...

This is basically the idea.  Don't want to over engineer too much to start off since GDAL does a lot of nice things, but I'm definitely interesting in seeing if it's any faster to make all of the network requests to access a COG tile async.

> COGDumper is not smart and doesn't do any spatial stuff

I wasn't aware of COGDumper.  We can definitely reuse a lot of that code,  thanks for pointing it out!


> but if we add pyproj we might be able to do;
> 
> * get geospatial info from the COG
> * fetch only the internal tile (and overview tiles) for a specific `.read` request.

I was thinking about something similar to a rasterio windows.

I'm going to break this up into multiple issues.

**Comment by geospatial-jeff** [comment]
Closing in favor of #2 #3
